language: node_js
node_js: 'node'

env:
  - EXTENSION_ID=

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
