name: Release

on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: last_release
          key: request_release
      - name: Release requested
        id: request_release
        run: |
          if [ ! -f "last_release" ] || [ "$(cat last_release)" != "$GITHUB_SHA" ]; then
            echo "::set-output name=request_release::1"
          fi
      - name: Use Node.js ${{ matrix.node-version }}
        if: contains(steps.request_release.outputs.request_release, '1')
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        if: contains(steps.request_release.outputs.request_release, '1')
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Generate release name
        if: contains(steps.request_release.outputs.request_release, '1')
        id: release_name
        run: |
          echo "::set-output name=version::$(npx daily-version)"
      - name: Create Release
        if: contains(steps.request_release.outputs.request_release, '1')
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_name.outputs.version }}
          release_name: Release ${{ steps.release_name.outputs.version }}
      - run: echo $GITHUB_SHA > last_release
      - name: Publish
        if: contains(steps.request_release.outputs.request_release, '1')
        run: npm run release
        env:
          VER: ${{ steps.release_name.outputs.version }}
          WEXT_SHIPIT_CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          WEXT_SHIPIT_CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          WEXT_SHIPIT_FIREFOX_JWT_ISSUER: ${{ secrets.JWT_USER }}
          WEXT_SHIPIT_FIREFOX_JWT_SECRET: ${{ secrets.JWT_SECRET }}
